prometheus:
  prometheusSpec:
    nodeSelector:
      node-role: monitoring
grafana:
  nodeSelector:
    node-role: monitoring
  adminPassword: admin123
alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role: monitoring
